SET CENTURY ON
SET DATE ITALIAN
SET DELETED ON
SET EXACT ON
SET EXCLUSIVE OFF
SET HOURS TO 24
SET NOTIFY OFF
SET POINT TO ","
SET REFRESH TO 1,1
SET REPROCESS TO 5
SET SAFETY OFF
SET SCOREBOARD OFF
SET SECONDS ON
SET SEPARATOR TO "."
SET STATUS BAR OFF
SET SYSMENU OFF
SET TALK OFF
SET TEXTMERGE NOSHOW